version: "3.9"

services:
  postgres:
    image: postgres:13.14-alpine3.19
    container_name: pg_auth
    restart: always
    env_file:
      - .env.pg
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - '5436:5432'

  redis:
    image: redis:alpine3.19
    container_name: redis_auth
    restart: always
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

  auth:
    build:
      context: .
    image: auth_grpc
    container_name: 'auth-service'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.jwt
      - .env.redis
      - .env.pg
    environment:
      WAIT_HOSTS: postgres:5432
    ports:
      - '5081:5081'

volumes:
  redis:
  pg: