app:
  name: 'auth-service'
  env: 'local'
  port: 5081

redis:
  host: 'localhost'
  port: 6379

pg:
  host: 'localhost'
  port: 5436
  db: 'auth'
  tls: 'disable'

jwt:
  accessTTL: 1
  refreshTTL: 24